name: Main Checks

on:
  pull_request:
  push:
    branches: [master]

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy

      - uses: Swatinem/rust-cache@v1

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings
      
      - name: Lint features
        run: |
          cargo clippy --all-targets -- --deny=warnings
          cargo clippy --all-features --all-targets -- --deny=warnings

      - name: Lint Writer
        run: |
          cargo clippy --all-targets -- --deny=warnings
          cargo clippy --all-features --all-targets -- --deny=warnings
        working-directory: packages/writer

      - name: Lint common
        run: |
          cargo clippy --all-targets -- --deny=warnings
          cargo clippy --all-features --all-targets -- --deny=warnings
        working-directory: packages/common

  clippy-release:
    name: Clippy release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy

      - uses: Swatinem/rust-cache@v1

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features --release -- -D warnings
        
      - name: Lint features
        run: |
          cargo clippy --all-targets -- --deny=warnings
          cargo clippy --all-features --all-targets -- --deny=warnings

      - name: Lint writer
        run: |
          cargo clippy --all-targets -- --deny=warnings
          cargo clippy --all-features --all-targets -- --deny=warnings
        working-directory: packages/writer

      - name: Lint common
        run: |
          cargo clippy --all-targets -- --deny=warnings
          cargo clippy --all-features --all-targets -- --deny=warnings
        working-directory: packages/common


  writer-test:
    name: Writer test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      
      - uses: Swatinem/rust-cache@v1

      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: wasm-pack

      - uses: browser-actions/setup-geckodriver@latest
      - uses: nanasess/setup-chromedriver@v1

      - name: Run Browser Tests
        run: |
          wasm-pack test --headless --firefox
          wasm-pack test --headless --chrome
        working-directory: packages/writer