name: Main Checks

on:
  pull_request:
  push:
    branches: [master]

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy

      - uses: Swatinem/rust-cache@v1

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings
      
      - name: Lint features
        run: |
          cargo clippy --all-targets -- --deny=warnings
          cargo clippy --all-features --all-targets -- --deny=warnings
  clippy-release:
    name: Clippy release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy

      - uses: Swatinem/rust-cache@v1

      - name: Run clippy
        uses: actions/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features --release -- -D warnings
        
      - name: Lint features
        run: |
          cargo clippy --all-targets -- --deny=warnings
          cargo clippy --all-features --all-targets -- --deny=warnings